function publish_csv_table (filename, fmt)
% PUBLISH_CSV_TABLE  Publish a benchmark CSV table to a destination format.
%
%   PUBLISH_CSV_TABLE(filename, fmt) If fmt == 'latex' then a LaTeX table stub
%      is created from input benchmark CSV (=comma separated value) table
%      'filename' in the same directory.  If fmt == 'html' then a standalone
%      HTML website of that tables is created in a subdirectory named 'html'
%      relative to the location of 'filename'.
%
%   See also benchmark.

% Copyright 2016-2018 Kai T. Ohlhus (kai.ohlhus@tuhh.de)

narginchk(2,2);

str = fileread (filename);
[pathstr, fname, fext] = fileparts (filename);
if (~strcmpi (fext, '.csv'))
  error ('VSDP:publish_csv_table:noCsvFile', ...
    'Input file must have ''.csv'' suffix.');
end
if (strcmp (fmt, 'html'))
  str = [html_header(fname), ...
    csv_to_html_table(str), ...
    html_footer([fname, fext])];
  if (exist ('html', 'dir') ~= 7)
    mkdir ('html')
  end
  outfile = fullfile(pathstr, 'html', [fname, '.html']);
elseif (strcmp(fmt, 'latex'))
  str = csv_to_latex_table (str);
  outfile = fullfile (pathstr, [fname, '.tex']);
end
str = strsplit (str, '\\n');
fid = fopen (outfile, 'w');
for j = 1:length(str)
  fprintf(fid, '%s\n', str{j});
end
fclose (fid);
end

function outstr = csv_to_latex_table (str)
str = strsplit(str,'\n');
thead = str{1};
thead = strrep (thead, ',', ' & ');
thead = strrep (thead, 'fU', '$fU$');
thead = strrep (thead, 'fL', '$fL$');
thead = strrep (thead, 'mu$fU$$fL$', '$\mu(fU,fL)$');
thead = strrep (thead, 'ts', '$t_s$');
thead = strrep (thead, 'tu', '$t_u$');
thead = strrep (thead, 'tl', '$t_l$');
thead = ['\hline\n', thead, ' \\\n\hline\n\endhead\n'];
tbody = strjoin (str(2:end), ' \\\\\n');
tbody = strrep(tbody, ',', ' & ');
outstr = [ ...
  '\begin{longtable}{', ...
  repmat('l', 1, length (strfind (thead, '&')) + 1), '}\n', ...
  thead, ...
  tbody, ...
  '\end{longtable}\n'];
end

function outstr = csv_to_html_table (str)
str = strsplit (str, '\n');
thead = str{1};
thead = strrep (thead, ',', '</th><th>');
thead = strrep (thead, 'fU', '$fU$');
thead = strrep (thead, 'fL', '$fL$');
thead = strrep (thead, 'mu$fU$$fL$', '$μ(fU,fL)$');
thead = strrep (thead, 'ts', '$t_s$');
thead = strrep (thead, 'tu', '$t_u$');
thead = strrep (thead, 'tl', '$t_l$');
thead = ['<thead>\n<tr><th>', thead, '</th></tr></thead>\n'];
tbody = strjoin (str(2:end), '</td></tr>\n<tr><td>');
tbody = strrep(tbody, ',', '</td><td>');
tbody = ['<tr><td>', tbody, '</td></tr>'];
tbody = strrep(tbody, '<tr><td></td></tr>', '');
tbody = ['<tbody>\n', tbody, ''];
outstr = [ ...
  '<table id=''main_tab''>\n', ...
  thead, ...
  tbody, ...
  '</table>\n', ...
  '<script type=''text/javascript''>', ...
  '$(document).ready( function () {\n', ...
  '  $(''#main_tab'').DataTable( {\n', ...
  '    ''lengthMenu'': [[10, 25, 50, -1], [10, 25, 50, ''All'']]\n', ...
  '  } );\n', ...
  '} );\n', ...
  '</script>\n'];
end

function outstr = html_header(tab_name)
jquery_str = ['<script ', ...
  'src=''https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js''>', ...
  '</script>\n'];
datatables_str = ['<link rel=''stylesheet'' type=''text/css'' ', ...
  'href=''https://cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css''>\n', ...
  '<script type=''text/javascript'' charset=''utf-8'' ', ...
  'src=''https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js''>', ...
  '</script>\n'];
mathjax_str = ['<script type=''text/x-mathjax-config''>\n', ...
  'MathJax.Hub.Config({\n', ...
  '  tex2jax: { inlineMath: [[''$'',''$''], [''\\('',''\\)'']] },\n', ...
  '  TeX: { equationNumbers: { autoNumber: ''all'' } }\n', ...
  '});\n', ...
  '</script>\n', ...
  '<script type=''text/javascript'' async ', ...
  'src=''https://cdn.mathjax.org/mathjax/latest/MathJax.js?', ...
  'config=TeX-MML-AM_CHTML''></script>\n'];
stylesheet_str = ['<style>\n', ...
  'body {\n', ...
  '  font-family: ''Roboto Condensed'', sans-serif;\n', ...
  '  padding-left: 7.5em;\n', ...
  '  padding-right: 7.5em;\n', ...
  '}\n', ...
  'footer {\n', ...
  '  margin-top: 2em;\n', ...
  '  font-size: 80%;\n', ...
  '}\n', ...
  'a, a:visited {\n', ...
  '  color: Blue;\n', ...
  '}\n', ...
  '</style>\n'];
outstr = ['<!DOCTYPE html>\n', ...
  '<html>\n', ...
  '<head>\n', ...
  '<meta charset=''UTF-8''>\n', ...
  '<title>Table "', tab_name, '"</title>\n', ...
  jquery_str, ...
  datatables_str, ...
  mathjax_str, ...
  stylesheet_str, ...
  '</head>\n', ...
  '<body>\n', ...
  '<h1>Table ''', tab_name, '''</h1>\n'];
end

function outstr = html_footer(tab_file)
outstr = ['\n', ...
  '<footer><hr>Original CSV data: ', ...
  '<a href=''../', tab_file, '''>', tab_file,'</a></footer>\n', ...
  '</body>\n', ...
  '</html>\n'];
end
