function obj = clear (obj, str)
% CLEAR  Clear 'all' or parts of a VSDP object.
%
%   See also vsdp.

% Copyright 2004-2018 Christian Jansson (jansson@tuhh.de)

str = validatestring (str, { ...
  'all', ...
  'Initial', ...
  'Approximate', ...
  'Rigorous lower bound', ...
  'Rigorous upper bound', ...
  'Certificate primal infeasibility', ...
  'Certificate dual infeasibility'});

switch (str)
  case 'all'
    obj = vsdp (obj);
  case {'Initial', 'Approximate', 'Rigorous lower bound', ...
      'Rigorous upper bound', 'Certificate primal infeasibility', ...
      'Certificate dual infeasibility'}
    obj.solutions(str) = [];
  otherwise
    error ('VSDP:clear:unknownCommand', ...
      'clear: Unknown command''%s''.', str);
end

end