function obj = clear (obj, str)
% CLEAR  Clear 'all' or parts of a VSDP object.
%
%   Detailed explanation goes here

str = validatestring (str, { ...
  'all', ...
  'Initial guess', ...
  'Approximate solution', ...
  'Rigorous lower bound', ...
  'Rigorous upper bound', ...
  'Certificate primal infeasibility', ...
  'Certificate dual infeasibility'});

switch (str)
  case 'all'
    obj = vsdp (obj);
  case {'Initial guess', 'Approximate solution', 'Rigorous lower bound', ...
      'Rigorous upper bound', 'Certificate primal infeasibility', ...
      'Certificate dual infeasibility'}
    obj.solutions(str) = [];
  otherwise
    error ('VSDP:clear:unknownCommand', ...
      'clear: Unknown command''%s''.', str);
end

end