# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "VSDP manual"
author: "C. Jansson et al."
copyright: "2018-2022"
logo: "res/sdp_cone.png"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: vsdp-2020-manual.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/vsdp/vsdp-2020
  path_to_book: "/doc"
  branch: master

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  extra_navbar: ""

launch_buttons:
  binderhub_url: ""
